/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : bigint,
  'customerPrincipal' : Principal,
  'text' : string,
  'timestamp' : bigint,
  'fromAdmin' : boolean,
}
export interface CustomerChat {
  'customer' : Principal,
  'messages' : Array<ChatMessage>,
  'customerId' : string,
}
export interface CustomerProfile {
  'principal' : Principal,
  'customerId' : string,
  'registeredAt' : bigint,
}
export interface Order {
  'id' : bigint,
  'videoFileName' : string,
  'status' : Status,
  'contactName' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
  'contactEmail' : string,
  'price' : bigint,
  'contactPhone' : string,
  'videoFileId' : string,
}
export type PaymentStatus = { 'Approved' : null } |
  { 'Cancelled' : null } |
  { 'Processing' : null } |
  { 'Pending' : null };
export interface PaymentStatusInfo {
  'status' : PaymentStatus,
  'contactName' : string,
  'orderId' : bigint,
  'updatedAt' : bigint,
  'customerId' : string,
  'price' : bigint,
}
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Status = { 'Cancelled' : null } |
  { 'InProgress' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approvePayment' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelPayment' : ActorMethod<[bigint], undefined>,
  'getAllChats' : ActorMethod<[], Array<CustomerChat>>,
  'getAllCustomers' : ActorMethod<[], Array<CustomerProfile>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllPaymentStatuses' : ActorMethod<[], Array<PaymentStatusInfo>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyChat' : ActorMethod<[], Array<ChatMessage>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getMyProfile' : ActorMethod<[], [] | [CustomerProfile]>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getOrderStats' : ActorMethod<
    [],
    {
      'total' : bigint,
      'pending' : bigint,
      'completed' : bigint,
      'inProgress' : bigint,
    }
  >,
  'getPaymentStatus' : ActorMethod<[bigint], PaymentStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isPaymentApproved' : ActorMethod<[bigint], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'selfRegister' : ActorMethod<[], string>,
  'sendAdminReply' : ActorMethod<[Principal, string], Result>,
  'sendCustomerMessage' : ActorMethod<[string], Result>,
  'setPaymentProcessing' : ActorMethod<[bigint], undefined>,
  'submitOrder' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'updateOrderStatus' : ActorMethod<[bigint, Status], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];