/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'customerPrincipal' : IDL.Principal,
  'text' : IDL.Text,
  'timestamp' : IDL.Int,
  'fromAdmin' : IDL.Bool,
});
export const CustomerChat = IDL.Record({
  'customer' : IDL.Principal,
  'messages' : IDL.Vec(ChatMessage),
  'customerId' : IDL.Text,
});
export const CustomerProfile = IDL.Record({
  'principal' : IDL.Principal,
  'customerId' : IDL.Text,
  'registeredAt' : IDL.Int,
});
export const Status = IDL.Variant({
  'Cancelled' : IDL.Null,
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'videoFileName' : IDL.Text,
  'status' : Status,
  'contactName' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'contactEmail' : IDL.Text,
  'price' : IDL.Nat,
  'contactPhone' : IDL.Text,
  'videoFileId' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Processing' : IDL.Null,
  'Pending' : IDL.Null,
});
export const PaymentStatusInfo = IDL.Record({
  'status' : PaymentStatus,
  'contactName' : IDL.Text,
  'orderId' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'customerId' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approvePayment' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelPayment' : IDL.Func([IDL.Nat], [], []),
  'getAllChats' : IDL.Func([], [IDL.Vec(CustomerChat)], ['query']),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(CustomerProfile)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllPaymentStatuses' : IDL.Func(
      [],
      [IDL.Vec(PaymentStatusInfo)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyChat' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(CustomerProfile)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrderStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'total' : IDL.Nat,
          'pending' : IDL.Nat,
          'completed' : IDL.Nat,
          'inProgress' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getPaymentStatus' : IDL.Func([IDL.Nat], [PaymentStatus], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isPaymentApproved' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'selfRegister' : IDL.Func([], [IDL.Text], []),
  'sendAdminReply' : IDL.Func([IDL.Principal, IDL.Text], [Result], []),
  'sendCustomerMessage' : IDL.Func([IDL.Text], [Result], []),
  'setPaymentProcessing' : IDL.Func([IDL.Nat], [], []),
  'submitOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, Status], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'customerPrincipal' : IDL.Principal,
    'text' : IDL.Text,
    'timestamp' : IDL.Int,
    'fromAdmin' : IDL.Bool,
  });
  const CustomerChat = IDL.Record({
    'customer' : IDL.Principal,
    'messages' : IDL.Vec(ChatMessage),
    'customerId' : IDL.Text,
  });
  const CustomerProfile = IDL.Record({
    'principal' : IDL.Principal,
    'customerId' : IDL.Text,
    'registeredAt' : IDL.Int,
  });
  const Status = IDL.Variant({
    'Cancelled' : IDL.Null,
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'videoFileName' : IDL.Text,
    'status' : Status,
    'contactName' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'contactEmail' : IDL.Text,
    'price' : IDL.Nat,
    'contactPhone' : IDL.Text,
    'videoFileId' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Processing' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const PaymentStatusInfo = IDL.Record({
    'status' : PaymentStatus,
    'contactName' : IDL.Text,
    'orderId' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'customerId' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approvePayment' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelPayment' : IDL.Func([IDL.Nat], [], []),
    'getAllChats' : IDL.Func([], [IDL.Vec(CustomerChat)], ['query']),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(CustomerProfile)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllPaymentStatuses' : IDL.Func(
        [],
        [IDL.Vec(PaymentStatusInfo)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyChat' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(CustomerProfile)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrderStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'pending' : IDL.Nat,
            'completed' : IDL.Nat,
            'inProgress' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getPaymentStatus' : IDL.Func([IDL.Nat], [PaymentStatus], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isPaymentApproved' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'selfRegister' : IDL.Func([], [IDL.Text], []),
    'sendAdminReply' : IDL.Func([IDL.Principal, IDL.Text], [Result], []),
    'sendCustomerMessage' : IDL.Func([IDL.Text], [Result], []),
    'setPaymentProcessing' : IDL.Func([IDL.Nat], [], []),
    'submitOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, Status], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };